version: "3"
services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./database/init_script.sql:/docker-entrypoint-initdb.d/init_script.sql
      - ./database/volume:/var/lib/postgresql/data
  
  scraper:
    image: avidito/ansuru-scraper:1
    command: sleep infinity
    environment:
      - DB_HOSTNAME=db
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_DATABASE=${POSTGRES_DB}
      - DB_PORT=${POSTGRES_PORT}
    volumes:
      - ./tmp:/app/tmp
    depends_on:
      - db
  
  dashboard-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${MB_DB_USER}
      - POSTGRES_PASSWORD=${MB_DB_PASS}
      - POSTGRES_DB=${MB_DB_DBNAME}
    
  dashboard:
    image: metabase/metabase:v0.43.5
    environment:
      - MB_DB_HOST=dashboard-db
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=${MB_DB_DBNAME}
      - MB_DB_PORT=${MB_DB_PORT}
      - MB_DB_USER=${MB_DB_USER}
      - MB_DB_PASS=${MB_DB_PASS}
      - MB_DB_FILE=/metabase-data/metabase.db
    ports:
      - 3000:3000
    volumes:
      - ./dashboard/db_volume:/var/lib/postgresql/data
      - ./dashboard/mb_volume:/metabase-data
    depends_on:
      - dashboard-db